add_friend/urls.py
from django.conf.urls import url
from .views import index , add_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),

]

profile_page/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

sambungin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import update_status.urls as update_status
import dashboard.urls as dashboard
import profile_page.urls as profile
from django.views.generic.base import RedirectView
import add_friend.urls as add_friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='update_status/', permanent = True), name = '$'),
    url(r'^update_status/', include(update_status, namespace='update_status')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
	url(r'^add_friend/', include(add_friend,namespace='add_friend')),

]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
]

add_friend/models.py
from django.db import models
from django.utils import timezone

class Friend(models.Model):
	
	def converTZ():
		return timezone.now() + timezone.timedelta(hours=0)
	
	name = models.CharField(max_length=27)
	url = models.CharField(max_length = 128)
	created_date = models.DateTimeField(default = converTZ)

	
# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

profile_page/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
    profile_pic = models.URLField(default="https://maxcdn.icons8.com/Share/icon/Users//user_male_circle_filled1600.png")
    name = models.CharField(max_length=27)
    birthday = models.CharField(max_length=6, default='01 Jan')
    gender = models.CharField(max_length=10)
    expertise = models.CharField(max_length=27)
    # expertise = models.ManyToManyField('Expertise')
    description = models.CharField(max_length=27)
    email = models.EmailField()
# 
# class Expertise(models.Model):
#     expertise = models.CharField(max_length=27)
#
#     def __str__(self):
#         return str(self.expertise)

update_status/models.py
from django.db import models

class Status(models.Model):
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

add_friend/forms.py
from django import forms

class AddFriend_Form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
		'invalid': 'Isi input dengan url',
	}
	attrs = {
		'class': 'form-control'
	}

	name = forms.CharField(label='Name',required=True, max_length=27,widget=forms.TextInput(attrs=attrs))
	url = forms.CharField(required=True, widget=forms.TextInput(attrs=attrs))

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'Apa yang ada di pikiran mu...'
    }
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import AddFriend_Form
from .models import Friend
# Create your views here.
response = {} 

def index(request):
	response['author'] = 'Muhammad Arief Wibowo'
	friend = Friend.objects.all()
	response['friends'] = friend
	html = 'add_friend/add_friend.html'
	response['friends_form'] = AddFriend_Form
	return render(request, html, response)

def add_friend(request):
	form = AddFriend_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		friends = Friend(name = request.POST['name'], url = request.POST['url'])
		friends.save() 
		return HttpResponseRedirect('/add_friend')

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from profile_page.models import Profile
from update_status.models import Status
from add_friend.models import Friend

response = {}
# Create your views here.
def index(request):
	html = 'dashboard.html'
	count_all_profiles = Profile.objects.count()
	if count_all_profiles == 0:
		profile = Profile.objects.create(
	            profile_pic='https://static.pexels.com/photos/247295/pexels-photo-247295.jpeg',
	            name='Katherine Wallace', birthday='November 30', gender='Female',
	            description='Stay positive!', email='mail@katewallace.com')
		profile.save()
	response['name']= Profile.objects.first().name
	response['profile_pic']= Profile.objects.first().profile_pic
	count = Status.objects.all().count()
	response['post_count']=count
	response['friend_count']=Friend.objects.all().count()
	if count > 0:
		response['description']=Status.objects.last().description
		response['time']=Status.objects.last().created_date
	else:
		response['description']="NO POSTS YET !!!"
		response['time']=""
	return render(request, html, response)

profile_page/views.py
from django.shortcuts import render
from .models import Profile

# Create your views here.

response = {}

def index(request):
    count_all_profiles = Profile.objects.count()

    # Create a new profile
    if count_all_profiles == 0:
        profile = Profile.objects.create(
            profile_pic='https://static.pexels.com/photos/247295/pexels-photo-247295.jpeg',
            name='Katherine Wallace', birthday='November 30', gender='Female', expertise='Walking, Breathing, Typing',
            description='Stay positive!', email='mail@katewallace.com')
        profile.save()

        # e1 = Expertise.objects.create(expertise='Fun Coding')
        # e1.save()
        # e2 = Expertise.objects.create(expertise='Modeling')
        # e2.save()
        # e3 = Expertise.objects.create(expertise='Taking Tests')
        # e3.save()
        #
        # profile.expertise.add(e1)
        # profile.expertise.add(e2)
        # profile.expertise.add(e3)
    else:
        profile = Profile.objects.first()

    # Inserting profile aspects into response
    response['profile_pic'] = profile.profile_pic
    response['name'] = profile.name
    response['birthday'] = profile.birthday
    response['gender'] = profile.gender
    # response['expertise'] = profile.expertise.all()
    response['description'] = profile.description
    response['email'] = profile.email

    # Specifying html
    html = 'profile_page.html'

    return render(request, html, response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

response = {}
# Create your views here.
def index(request):
	response['author'] = "Nurhikmah ilmi"
	todo = Status.objects.all()
	response['status'] = todo
	html = 'update_status.html'
	response['status_form'] = Status_Form
	return render(request, html, response)

def add_status(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['description'] = request.POST['description']
		todo = Status(description=response['description'])
		todo.save()
		return HttpResponseRedirect('/update_status/')
	else:
		return HttpResponseRedirect('/update_status/')

add_friend/templates/add_friend/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>SambungIn Official Website</title>
	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<header>
		{% include "add_friend/partials/header.html" %}
	</header>

	<content>
		{% block content %}

		{% endblock %}	
	</content>

	<footer>
		{% block footer %}
        {% include "add_friend/partials/footer.html" %}
        {% endblock %}
	</footer>


</body>
</html>

add_friend/templates/add_friend/partials/footer.html
<p> &copy; Sambungin Developer Team </p>

add_friend/templates/add_friend/partials/header.html
<nav class="navbar navbar-default bg-faded">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="button1 navbar-toggle" data-toggle = "collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="header.html" id="logo"><h1>Sambung.In</h1></a>
		</div>

		<div class=" collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right" >
				{% load static %}
				<li class="list-menu"><a href="{% url 'update_status:index' %}"><img src="{%static "status.png" %}" alt="status" class="icon" name="Status" /></a></li>
				<li class="list-menu"><a href="{% url 'profile:index' %}"><img src="{%static "profle.png" %}" alt="profile"  class="icon"/></a></li>
				<li class="list-menu"><a href="{% url 'add_friend:index' %}" ><img src="{%static "addfriend.png" %}" alt="addfriend" class="icon"/></a></li>
				<li class="list-menu"><a href="{% url 'dashboard:index' %}"><img src="{%static "stats.png" %}" alt="stats" class="icon"/></a></li>
			</ul>
		</div>

	</div>
</nav>

dashboard/templates/dashboard.html
<!DOCTYPE html>
{% extends "layout/base.html" %}
{% load static %}
{% block content %}

<style>
body{
  background-color: lightgray;
}
.photo{
    border-radius: 50%;
    height: 200px;
    width: 200px;
    object-fit: cover;
    display: inline-block;
}
#name-post{
	font-size: 20px;
	display: inline;
}
.main-title{
    color: black;
    font-family: "Century Gothic";
    font-weight: bold;
    font-size: 25px;
    margin-left: 8%;
}
.profile{
	display: inline-block;
	margin-left: 15%;
}

.stats{
    margin: 20px;
    text-align:center;
    color: #2c093d;
    font-size: 20px;
    font-family: "Century Gothic"
}
.friends-count{
    display: inline-block;
    border-radius: 15px;
    border-spacing: 10px;
    padding: 9px 12px 9px 12px;
    background: lightblue;  /* fallback for old browsers */
    background: -webkit-linear-gradient(to right, lightblue, #d381f9);  /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to right, lightblue, #d381f9 ); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}
.feeds-count{
    margin-left: 30%;
    display: inline-block;
    border-radius: 15px;
    border-spacing: 10px;
    padding: 9px 12px 9px 12px;
    background: lightblue;  /* fallback for old browsers */
    background: -webkit-linear-gradient(to right, lightblue, #d381f9);  /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to right, lightblue, #d381f9);
}
#friends{
	display: inline-block;
}
#total-friends{
	display: inline-block;
}
#feeds{
	display: inline-block;
}
#total-feeds{
	display: inline-block;
}
.latest{
    border-top: thick double black;
    width: 75%;
    margin: auto;
    padding: 10px;
    font-family: "Century Gothic"
}

.update-status-date-added{
    background: lightgray;
}
.update-status-description{
    margin: 15px;
}
.photo-post{
    display: inline-block;
    background: white;
    border-radius: 50%;
    height: 50px;
    width: 50px;
    object-fit: cover;
    display: inline-block;
}
#name{
	font-size: 30px;
	display: inline;
	font-family: "Century Gothic"
}

</style>
<h1 class="main-title">Statistic</h1>
<div class ="profile">
        <h2>
        <img class="photo" src= {{ profile_pic }} >
        <p id="name"> {{ name }}</p>
        </h2>
</div>
<div class = "stats">
      <div class = "friends-count">
        <p id="friends"> Friends</p>
        <p id="total-friends"> {{ friend_count}} </p>
      </div>
      <div class = "feeds-count">
        <p id="feeds"> Feed</p>
        <p id="total-feeds"> {{post_count}} Posts </p>
      </div>
</div>
<div class="latest">
        <h2 id="latest"> Latest Post</h2>
        <div class="media">
            <div class="media-body">
                 <div class="update-status-title">
                    <h3>
                    <img class="photo-post" src={{ profile_pic }}>
                    <p id="name-post"> {{ name }} </p>
                    </h3>
                </div>
                <div class="update-status-description">
                    {{description}}
                </div>
                <div class="update-status-date-added">
                    Posted on {{time}}
                </div>
            </div>
        </div>
</div>
{% endblock %}

dashboard/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'add_friend.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
         <title>Dashboard</title>
    </head>
    <body>
        <header>
            {% include "partials/header.html" %}
        </header>
        <content>
                <div class="">
                    {% block content %}
                        <!-- content goes here -->
                    {% endblock %}
                </div>
        </content>
        <footer>
      		{% block footer %}
              {% include "add_friend/partials/footer.html" %}
              {% endblock %}
      	</footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        <script type="application/javascript">
          $(function() {
              $('a[href*="#"]:not([href="#"])').click(function() {
                if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                  var target = $(this.hash);
                  target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                  if (target.length) {
                    $('html, body').animate({
                      scrollTop: target.offset().top - 55
                    }, 1000);
                    return false;
                  }
                }
              });
            });
        </script>
     </body>
</html>

dashboard/templates/partials/footer.html
<p> &copy; Sambungin Developer Team </p>

dashboard/templates/partials/header.html
<nav class="navbar navbar-default bg-faded">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="button1 navbar-toggle" data-toggle = "collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="header.html" id="logo"><h1>Sambung.In</h1></a>
		</div>

		<div class=" collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right" >
				{% load static %}
				<li class="list-menu"><a href="{% url 'update_status:index' %}"><img src="{%static "status.png" %}" alt="status" class="icon" name="Status" /></a></li>
				<li class="list-menu"><a href="{% url 'profile:index' %}"><img src="{%static "profle.png" %}" alt="profile"  class="icon"/></a></li>
				<li class="list-menu"><a href="{% url 'add_friend:index' %}" ><img src="{%static "addfriend.png" %}" alt="addfriend" class="icon"/></a></li>
				<li class="list-menu"><a href="{% url 'dashboard:index' %}"><img src="{%static "stats.png" %}" alt="stats" class="icon"/></a></li>
			</ul>
		</div>

	</div>
</nav>

profile_page/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'add_friend.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'profile_page.css' %}">
         <title>Profile Page</title>
    </head>
    <body>
        <header>
            {% include "partials/header.html" %}
        </header>
        <content>
                <div class="">
                    {% block content %}
                        <!-- content goes here -->
                    {% endblock %}
                </div>
        </content>
        <footer>
      		{% block footer %}
              {% include "add_friend/partials/footer.html" %}
              {% endblock %}
      	</footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        <script type="application/javascript">
          $(function() {
              $('a[href*="#"]:not([href="#"])').click(function() {
                if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                  var target = $(this.hash);
                  target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                  if (target.length) {
                    $('html, body').animate({
                      scrollTop: target.offset().top - 55
                    }, 1000);
                    return false;
                  }
                }
              });
            });
        </script>
     </body>
</html>

profile_page/templates/partials/footer.html
<p> &copy; Sambungin Developer Team </p>

profile_page/templates/partials/header.html
<nav class="navbar navbar-default bg-faded">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="button1 navbar-toggle" data-toggle = "collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="header.html" id="logo"><h1>Sambung.In</h1></a>
		</div>

		<div class=" collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right" >
				{% load static %}
				<li class="list-menu"><a href="{% url 'update_status:index' %}"><img src="{%static "status.png" %}" alt="status" class="icon" name="Status" /></a></li>
				<li class="list-menu"><a href="{% url 'profile:index' %}"><img src="{%static "profle.png" %}" alt="profile"  class="icon"/></a></li>
				<li class="list-menu"><a href="{% url 'add_friend:index' %}" ><img src="{%static "addfriend.png" %}" alt="addfriend" class="icon"/></a></li>
				<li class="list-menu"><a href="{% url 'dashboard:index' %}"><img src="{%static "stats.png" %}" alt="stats" class="icon"/></a></li>
			</ul>
		</div>

	</div>
</nav>

profile_page/templates/profile_page.html
<!DOCTYPE html>
{% extends "layout/base.html" %}
{% load static %}

{% block content %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/profile_page.css' %}"/>
    <h1> Profile Page of {{ name }} </h1>
    <div id="profile_picture">
        <img src="{{ profile_pic }}" class="center">
    </div>
    <div id="name">
    {{ name }}
    </div>
    <div id="bio">
    <div class="container">
        <div class="row">
            <div class="col-md-6" class="subject">Birthday</div>
            <div class="col-md-6" class="value">{{ birthday }}</div>
        </div>
        <div class="row">
            <div class="col-md-6" class="subject">Gender</div>
            <div class="col-md-6" class="value">{{ gender }}</div>
        </div>
        <div class="row">
            <div class="col-md-6" class="subject">Expertise</div>
            <div class="col-md-6" class="value">{% for object in expertise %}
                <div class = "expertise">{{ object }}</div>
            {% endfor %}</div>
        </div>
        <div class="row">
            <div class="col-md-6" class="subject">Description</div>
            <div class="col-md-6" class="value">{{ description }}</div>
        </div>
        <div class="row">
            <div class="col-md-6" class="subject">Email</div>
            <div class="col-md-6" class="value">{{ email }}</div>
        </div>
    </div>
    </div>
{% endblock %}

update_status/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}">
         <title>Sambungin</title>
    </head>
    <body>
        <header>
            {% include "partials/header.html" %}
        </header>
        <content>
                <div class="">
                    {% block content %}
                        <!-- content goes here -->
                    {% endblock %}
                </div>
        </content>
        <footer>
      		{% block footer %}
              {% include "add_friend/partials/footer.html" %}
              {% endblock %}
      	</footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        <script type="application/javascript">
          $(function() {
              $('a[href*="#"]:not([href="#"])').click(function() {
                if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                  var target = $(this.hash);
                  target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                  if (target.length) {
                    $('html, body').animate({
                      scrollTop: target.offset().top - 55
                    }, 1000);
                    return false;
                  }
                }
              });
            });
        </script>
     </body>
</html>

update_status/templates/partials/footer.html
<p> &copy; Sambungin Developer Team </p>

update_status/templates/partials/header.html
<nav class="navbar navbar-default bg-faded">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="button1 navbar-toggle" data-toggle = "collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="header.html" id="logo"><h1>Sambung.In</h1></a>
		</div>

		<div class=" collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right" >
				{% load static %}
				<li class="list-menu"><a href="{% url 'update_status:index' %}"><img src="{%static "status.png" %}" alt="status" class="icon" name="Status" /></a></li>
				<li class="list-menu"><a href="{% url 'profile:index' %}"><img src="{%static "profle.png" %}" alt="profile"  class="icon"/></a></li>
				<li class="list-menu"><a href="{% url 'add_friend:index' %}" ><img src="{%static "addfriend.png" %}" alt="addfriend" class="icon"/></a></li>
				<li class="list-menu"><a href="{% url 'dashboard:index' %}"><img src="{%static "stats.png" %}" alt="stats" class="icon"/></a></li>
			</ul>
		</div>

	</div>
</nav>